IF NOT EXISTS(SELECT TOP 1 * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'AspNetUsers' AND COLUMN_NAME = 'IsAdmin')
BEGIN
	ALTER TABLE [dbo].[AspNetUsers] ADD IsAdmin TINYINT NULL
END
go

IF NOT EXISTS(SELECT TOP 1 * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'AspNetUsers' AND COLUMN_NAME = 'Address')
BEGIN
	ALTER TABLE [dbo].[AspNetUsers] ADD Address NVARCHAR(500) NULL
END
go	

IF NOT EXISTS(SELECT TOP 1 * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'AspNetUsers' AND COLUMN_NAME = 'DateOfBirth')
BEGIN
	ALTER TABLE [dbo].[AspNetUsers] ADD DateOfBirth DateTime NULL
END
go

IF NOT EXISTS(SELECT TOP 1 * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'AspNetUsers' AND COLUMN_NAME = 'ProfilePicturePath')
BEGIN
	ALTER TABLE [dbo].[AspNetUsers] ADD ProfilePicturePath NVARCHAR(500) NULL
END
go	
